[package]
name = "market"
version = "0.1.0"
edition = "2021"

[dependencies]
utility = { version = "0.1.0", path = "../utility"}
binance = { version = "0.1.0", path = "./cex/binance"}
ftx = { version = "0.1.0", path = "./cex/ftx"}